### ISSUE TITLE
京东首页秒杀

### ISSUE THREAD

**Issue by XiaoHb233** [jf3096/jd-puppeteer-yuyue#1]
可以爬店铺活动和京东首页秒杀的商品吗

**Comment by jf3096** [comment]
原则上可以, 只是这个是我随手写的.  因为花了1小时研究京东接口, 过于麻烦. 
所以直接以 puppeteer 快速爬数据, 用于抢显卡. 没显卡, 哎

**Comment by XiaoHb233** [comment]
> 原则上可以, 只是这个是我随手写的. 因为花了1小时研究京东接口, 过于麻烦.
> 所以直接以 puppeteer 快速爬数据, 用于抢显卡. 没显卡, 哎

node报错：
node:19756) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'index.html'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at CronJob.starter (C:\Users\XHB\Desktop\jd-puppeteer-yuyue-master\index.js:87:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19756) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'index.html'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at starter (C:\Users\XHB\Desktop\jd-puppeteer-yuyue-master\index.js:87:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:19756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by AlgoNetwork** [comment]
显卡太tm 贵了。。。。比特币啥时候能暴跌

**Comment by jf3096** [comment]
重新看一下 README, 我更新了
1. 使用说明
2. 一个部署的测试地址, 你可以直接拿来看
