### ISSUE TITLE
npm已经更新过了，还是不行

### ISSUE THREAD

**Issue by kof8855** [jf3096/jd-puppeteer-yuyue#4]
[root@3p3acaczzhotb9ut-0713535 jd-puppeteer-yuyue]# node index
/root/jd-puppeteer-yuyue/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:80
                    throw new Error(missingText);
                          ^

Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (856583).
    at ChromeLauncher.launch (/root/jd-puppeteer-yuyue/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:80:27)
    at async starter (/root/jd-puppeteer-yuyue/index.js:28:19)

**Comment by jf3096** [comment]
你的网络情况问题哦，可以挂代理或者了解一下这个：https://github.com/gucong3000/mirror-config-china

**Comment by 891809266** [comment]
感觉不是网络的问题，我全局install 也会报这个错误
